language: python
python:
  - "2.7.16"
  - "3.9.6"
  - "pypy"
  - "pypy3"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install .
# command to run tests
script:
  - pytest